/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdopterCenter;

import Entity.Adopter.Adopter;
import Entity.Adopter.AdopterDirectory;
import Entity.Adopter.AdopterInfo;
import Entity.AdopterCenter.AdopterCenter;
import Entity.Center.RescueCenterDirectory;
import Entity.StrayAnimal.StrayAnimal;
import Interface.Adopter.ViewAnimalDetailsJpanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ManageAdopterRequestJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdopterRequestJpanel
     */
    private JPanel rightpanel;
    private AdopterCenter adoptercenter;
    private AdopterDirectory addir;
    private StrayAnimal strayanimal;
    
    public ManageAdopterRequestJpanel(JPanel rightpanel, AdopterDirectory addir, StrayAnimal strayanimal, AdopterCenter adoptercenter) {
        initComponents();
        this.rightpanel = rightpanel;
        this.addir = addir;
        this.strayanimal = strayanimal;
        this.adoptercenter = adoptercenter;
        
        populate();
    }
    public void populate(){
        int rowCount = adopterTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)adopterTable.getModel();
        jScrollPane1.getViewport().setBackground(new Color(249,246,246));
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        
        for(Adopter adopter : adoptercenter.getAdopterDir().getAdopterDirectory()){
            Object row[] = new Object[dtm.getColumnCount()];
            row[0] = adopter;
            row[1] = adopter.getUserInfo().getEmail();
            row[2] = adopter.getUserInfo().getSalary();
            row[3] = adopter.getUserInfo().getTypeList();
            row[4] = adopter.getStatus();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adopterTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AcceptBtn = new javax.swing.JButton();
        RejectBtn = new javax.swing.JButton();
        DetailsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/AdopterCenter/adoptercenter.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 570));

        jPanel3.setBackground(new java.awt.Color(247, 244, 244));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 236, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 570));

        jPanel1.setBackground(new java.awt.Color(247, 244, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        adopterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Name", "Adopter Email", "Adopter Salary", "Adopter Animal ", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adopterTable);
        if (adopterTable.getColumnModel().getColumnCount() > 0) {
            adopterTable.getColumnModel().getColumn(0).setResizable(false);
            adopterTable.getColumnModel().getColumn(1).setResizable(false);
            adopterTable.getColumnModel().getColumn(2).setResizable(false);
            adopterTable.getColumnModel().getColumn(3).setResizable(false);
            adopterTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText(" Manage Adopter Request");

        AcceptBtn.setBackground(new java.awt.Color(255, 255, 255));
        AcceptBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        AcceptBtn.setText("Accept");
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });

        RejectBtn.setBackground(new java.awt.Color(255, 255, 255));
        RejectBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        RejectBtn.setText("Reject");
        RejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectBtnActionPerformed(evt);
            }
        });

        DetailsBtn.setBackground(new java.awt.Color(255, 255, 255));
        DetailsBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        DetailsBtn.setText("Details");
        DetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(RejectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(DetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RejectBtn)
                    .addComponent(AcceptBtn)
                    .addComponent(DetailsBtn))
                .addGap(121, 121, 121))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 590, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = adopterTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Adopter adop = (Adopter)adopterTable.getValueAt(selectedRow, 0);
            adop.setStatus("Permitted");
            adop.getAnimalDir().addStrayAnimal(strayanimal);
            JOptionPane.showMessageDialog(null, "Change Status Sucessfully!");
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        
        populate();
        
    }//GEN-LAST:event_AcceptBtnActionPerformed

    private void RejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow1 = adopterTable.getSelectedRow();
        
        if(selectedRow1 >= 0)
        {   
            Adopter adopter = (Adopter)adopterTable.getValueAt(selectedRow1, 0);
            adopter.setStatus("Rejected");
            JOptionPane.showMessageDialog(null, "Change Status Sucessfully!");
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        
        populate();
    }//GEN-LAST:event_RejectBtnActionPerformed

    private void DetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = adopterTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Adopter adopter = (Adopter)adopterTable.getValueAt(selectedRow, 0);
            AdopterInformationJpanel aipanel = new AdopterInformationJpanel(rightpanel, adopter);
            rightpanel.add(aipanel);
            CardLayout layout = (CardLayout) rightpanel.getLayout();
            layout.next(rightpanel);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_DetailsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton DetailsBtn;
    private javax.swing.JButton RejectBtn;
    private javax.swing.JTable adopterTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
