/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Hospital;

import Entity.Hospital.PetHospital;
import Entity.System.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class ManageEnterpriseJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJpanel
     */
    private EcoSystem ecoSystem;
    private PetHospital petHospital;
    
    public ManageEnterpriseJpanel(JPanel rightpanel, EcoSystem ecoSystem, PetHospital petHospital) {
        initComponents();
        this.rightpanel = rightpanel;
        this.ecoSystem = ecoSystem;
        this.petHospital = petHospital;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        ManageEnterpriseBtn = new javax.swing.JButton();
        ManageEmployeeBtn = new javax.swing.JButton();
        rightpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 634));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(700, 617));

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel1.setPreferredSize(new java.awt.Dimension(160, 613));

        ManageEnterpriseBtn.setBackground(new java.awt.Color(255, 255, 255));
        ManageEnterpriseBtn.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        ManageEnterpriseBtn.setText("Manage Enterprise");
        ManageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseBtnActionPerformed(evt);
            }
        });

        ManageEmployeeBtn.setBackground(new java.awt.Color(255, 255, 255));
        ManageEmployeeBtn.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        ManageEmployeeBtn.setText("Manage Employee");
        ManageEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEmployeeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManageEnterpriseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(ManageEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(ManageEnterpriseBtn)
                .addGap(129, 129, 129)
                .addComponent(ManageEmployeeBtn)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        rightpanel.setBackground(new java.awt.Color(249, 246, 246));
        rightpanel.setMinimumSize(new java.awt.Dimension(0, 0));
        rightpanel.setPreferredSize(new java.awt.Dimension(550, 613));
        rightpanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Hospital/hospital1.png"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(650, 614));
        rightpanel.add(jLabel1, "card2");

        jSplitPane1.setRightComponent(rightpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseBtnActionPerformed
        // TODO add your handling code here:
        ManageHospitalInformationJpanel mhipanel = new ManageHospitalInformationJpanel(rightpanel, ecoSystem, petHospital);
        this.rightpanel.add(mhipanel);
        CardLayout layout = (CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
    }//GEN-LAST:event_ManageEnterpriseBtnActionPerformed

    private void ManageEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEmployeeBtnActionPerformed
        // TODO add your handling code here:
        ManageHospitalEmplyeeJpanel mhepanel = new ManageHospitalEmplyeeJpanel(rightpanel, ecoSystem, petHospital);
        this.rightpanel.add(mhepanel);
        CardLayout layout = (CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
    }//GEN-LAST:event_ManageEmployeeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEmployeeBtn;
    private javax.swing.JButton ManageEnterpriseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel rightpanel;
    // End of variables declaration//GEN-END:variables
}
