/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.DB4OUtil.DB4OUtil;
import Entity.Adopter.Adopter;
import Entity.Adopter.AdopterDirectory;
import Entity.AdopterCenter.AdopterCenter;
import Entity.AdopterCenter.AdopterCenterDirectory;
import Entity.Center.RescueCenter;
import Entity.Center.RescueCenterDirectory;
import Entity.EnterpriseDirectory.EnterpriseDirectory;
import Entity.Hospital.PetHospital;
import Entity.Hospital.PetHospitalDirectory;
import Entity.Network.Network;
import Entity.StrayAnimal.StrayAnimal;
import Entity.System.EcoSystem;
import Interface.Admain.Admain;
import Interface.Admain.AdminManageJpanel;
import Interface.Adopter.AdopterLoginJpanel;
import Interface.AdopterCenter.AdopterCenterLogin;
import Interface.AdopterCenter.ManageAdopterCenterEmplyeeJpanel;
import Interface.AdopterCenter.ManageAdopterRequestJpanel;
import Interface.ExitSystem.ExitPanel;
import Interface.Hospital.HospitalLoginJpanel;
import Interface.Hospital.ManageEnterpriseJpanel;
import Interface.Hospital.ManageHospitalJpanel;
import Interface.RescueCenter.ManageCenterEmplyeeJpanel;
import Interface.RescueCenter.ManageRescueCenterJpanel;
import Interface.RescueCenter.RescueCenterLoginJpanel;


import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author liumingyu
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private PetHospitalDirectory petHospitalDirectory;
    private RescueCenterDirectory rcdir;
    private RescueCenter resc;
    private EcoSystem ecoSystem;
    private EnterpriseDirectory erdir;
    private AdopterDirectory addir;
    private StrayAnimal strayanimal;
    DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    private JPanel initiatepanel;
    
    public MainJFrame() {
        initComponents();
        this.initiatepanel = this.RightPanel;
        petHospitalDirectory = new PetHospitalDirectory();
        rcdir = new RescueCenterDirectory();
        resc = new RescueCenter();
        ecoSystem = dB4OUtil.retrieveSystem();
        erdir = new EnterpriseDirectory();
        addir = new AdopterDirectory();
        strayanimal = new StrayAnimal();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                //int flag = JOptionPane.showConfirmDialog(null, "Exit?", "Care!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(null, "Exit Successfully!");
                dB4OUtil.storeSystem(ecoSystem);
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LeftPanel = new javax.swing.JPanel();
        AdopterBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        mapButton = new javax.swing.JButton();
        googleButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));

        LeftPanel.setBackground(new java.awt.Color(249, 246, 246));
        LeftPanel.setPreferredSize(new java.awt.Dimension(120, 501));

        AdopterBtn.setBackground(new java.awt.Color(255, 255, 255));
        AdopterBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        AdopterBtn.setText("Adopter");
        AdopterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdopterBtnActionPerformed(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExitBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("User Name:");

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Password:");

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        mapButton.setBackground(new java.awt.Color(255, 255, 255));
        mapButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        mapButton.setText("Open Map");
        mapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapButtonActionPerformed(evt);
            }
        });

        googleButton.setBackground(new java.awt.Color(255, 255, 255));
        googleButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        googleButton.setText("Google Search");
        googleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/google.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Googlemap.png"))); // NOI18N

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdopterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordField)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(googleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(logoutButton))
                .addGap(64, 64, 64)
                .addComponent(AdopterBtn)
                .addGap(40, 40, 40)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(googleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapButton)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addComponent(ExitBtn)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(LeftPanel);

        RightPanel.setBackground(new java.awt.Color(249, 246, 246));
        RightPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        RightPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        RightPanel.setPreferredSize(new java.awt.Dimension(639, 501));
        RightPanel.setLayout(new java.awt.CardLayout());

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Page.png"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RightPanel.add(jLabel3, "card2");

        jSplitPane1.setRightComponent(RightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        RightPanel.removeAll();
        ExitPanel epanel = new ExitPanel(RightPanel, ecoSystem, dB4OUtil);
        this.RightPanel.add(epanel);
        ((java.awt.CardLayout)RightPanel.getLayout()).next(RightPanel);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void AdopterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdopterBtnActionPerformed
        // TODO add your handling code here:
        RightPanel.removeAll();
        AdopterLoginJpanel alpanel = new AdopterLoginJpanel(RightPanel, ecoSystem, addir);
        this.RightPanel.add(alpanel);
        ((java.awt.CardLayout)RightPanel.getLayout()).next(RightPanel);
    }//GEN-LAST:event_AdopterBtnActionPerformed

    private void googleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleButtonActionPerformed
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);

        JFrame frame = new JFrame();
        frame.add(view, BorderLayout.CENTER);
        frame.setSize(1200, 800);
        frame.setVisible(true);

        browser.loadURL("https://www.google.com");
    }//GEN-LAST:event_googleButtonActionPerformed

    private void mapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapButtonActionPerformed
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);

        JFrame frame = new JFrame();
        frame.add(view, BorderLayout.CENTER);
        frame.setSize(1200, 800);
        frame.setVisible(true);

        browser.loadURL("https://www.google.com/maps/");
    }//GEN-LAST:event_mapButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = this.userNameField.getText();
        String password = this.passwordField.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be empty!");
            return;
        }
        if(username.equals("")){
            JOptionPane.showMessageDialog(null, "Username cannot be empty!");
            return;
        }
        
        if(username.equals("zhu")&&password.equals("zhu")){
            JOptionPane.showMessageDialog(null, "Login as an admin successfully!");
            AdminManageJpanel ampanel = new AdminManageJpanel(RightPanel, ecoSystem);
            this.RightPanel.add(ampanel);
            CardLayout layout = (CardLayout)RightPanel.getLayout();
            layout.next(RightPanel);
            return;
        }
        
        for(Network nowNetwork : this.ecoSystem.getNetworkDir().getNetworkList()){
            RescueCenterDirectory rcd = nowNetwork.getEnterpriseDir().getRescuecenterDir();
            for(RescueCenter nowrc: rcd.getRcd()){
                if(nowrc.getManageraccountDir().VerifyAccount(username, password)){
                    JOptionPane.showMessageDialog(null, "Login as a RescueCenter Manager Successfully!");
                    ManageCenterEmplyeeJpanel mrcipanel = new ManageCenterEmplyeeJpanel(RightPanel,ecoSystem, nowrc);       
                    RightPanel.add(mrcipanel);
                    CardLayout layout = (CardLayout)RightPanel.getLayout();
                    layout.next(RightPanel);
                    return;
                }
                if(nowrc.getEmployeeaccountDir().VerifyAccount(username, password)){
                    JOptionPane.showMessageDialog(null, "Login as an RescueCenter Enployee successfully!");
                    ManageRescueCenterJpanel mrcpanel = new ManageRescueCenterJpanel(RightPanel,ecoSystem, nowrc, petHospitalDirectory);       
                    RightPanel.add(mrcpanel);
                    CardLayout layout = (CardLayout)RightPanel.getLayout();
                    layout.next(RightPanel);     
                    return;     
                }
                        
            }
            
            PetHospitalDirectory phd = nowNetwork.getEnterpriseDir().getPethospitalDir();
            for(PetHospital nowph : phd.getPetHospitalList()){
                if(nowph.getManageraccountDir().VerifyAccount(username, password)){
                    JOptionPane.showMessageDialog(null, "Login as a Hospital Manager Successfully!");
                    ManageEnterpriseJpanel mepanel = new ManageEnterpriseJpanel(RightPanel, ecoSystem, nowph);      
                    RightPanel.add(mepanel);
                    CardLayout layout = (CardLayout)RightPanel.getLayout();
                    layout.next(RightPanel);
                    return;
                }
                if(nowph.getEmployeeaccountDir().VerifyAccount(username, password)){
                    JOptionPane.showMessageDialog(null, "Login as an Hospital Enployee successfully!");
                    ManageHospitalJpanel mhpanel = new ManageHospitalJpanel(RightPanel, ecoSystem, nowph);       
                    RightPanel.add(mhpanel);
                    CardLayout layout = (CardLayout)RightPanel.getLayout();
                    layout.next(RightPanel);
                    return; 
                }
               
            }
            
            AdopterCenterDirectory acd = nowNetwork.getEnterpriseDir().getAdoptercenterDir();
            for(AdopterCenter nowac : acd.getAdopterCenterDir()){
                if(nowac.getManageraccountDir().VerifyAccount(username, password)){
                    JOptionPane.showMessageDialog(null, "Login as a Adopter Center Manager Successfully!");
                    ManageAdopterCenterEmplyeeJpanel macpanel = new ManageAdopterCenterEmplyeeJpanel(RightPanel,nowac, this.ecoSystem);       
                    RightPanel.add(macpanel);
                    CardLayout layout = (CardLayout)RightPanel.getLayout();
                    layout.next(RightPanel);
                    return;
                }
                if(nowac.getEmployeeaccountDir().VerifyAccount(username, password)){
                    JOptionPane.showMessageDialog(null, "Login as an Adopter Center Enployee successfully!");
                    ManageAdopterRequestJpanel marpanel = new ManageAdopterRequestJpanel(RightPanel,addir,strayanimal, nowac);       
                    RightPanel.add(marpanel);
                    CardLayout layout = (CardLayout)RightPanel.getLayout();
                    layout.next(RightPanel);
                    return; 
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Wrong username or password");
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        initiatePanel initiatep = new initiatePanel();       
        RightPanel.add(initiatep);
        CardLayout layout = (CardLayout)RightPanel.getLayout();
        layout.next(RightPanel);
        this.userNameField.setText("");
        this.passwordField.setText("");
        return; 
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdopterBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton googleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mapButton;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
