/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.RescueCenter;

import Entity.Center.RescueCenter;
import Entity.Center.RescueCenterDirectory;
import Entity.StrayAnimal.StrayAnimal;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class CreateAnimalJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAnimalJpanel
     */
    private JPanel createpanel;
    private RescueCenter rescuecenter;
    
    
    public CreateAnimalJpanel(JPanel createpanel, RescueCenter rescuecenter) {
        initComponents();
        this.createpanel = createpanel;
        this.rescuecenter = rescuecenter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnimalTypeTxt = new javax.swing.JTextField();
        AddressTxt = new javax.swing.JTextField();
        DescriptionTxt = new javax.swing.JTextField();
        CreateBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(881, 614));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AnimalTypeTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        add(AnimalTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 215, 37));

        AddressTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 215, 36));

        DescriptionTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        add(DescriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 364, 215, 160));

        CreateBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });
        add(CreateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 120, -1));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BackBtn.setText("Back <<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/RescueCenter/Label.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, 830, 120));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 140));

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel1.setText("Animal Species:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 147, 32));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Description：");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 135, 28));

        IDTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jPanel2.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 215, 38));

        jLabel5.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel5.setText("ID：");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel3.setText("Status：");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 30));

        StatusComboBox.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Healthy", "Disable", "Illed" }));
        jPanel2.add(StatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 220, -1));

        jLabel2.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel2.setText("Address of Find：");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 173, 31));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 850, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        createpanel.remove(this);
        Component[] componentArray = createpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRescueCenterJpanel mfpanel = (ManageRescueCenterJpanel) component;
        mfpanel.populate();
        CardLayout layout = (CardLayout) createpanel.getLayout();
        layout.previous(createpanel);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        if(AddressTxt.getText().isEmpty() || DescriptionTxt.getText().isEmpty() || IDTxt.getText().isEmpty() || AnimalTypeTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some input text is empty!");
            AddressTxt.setText("");
            DescriptionTxt.setText("");
            IDTxt.setText("");
            AnimalTypeTxt.setText("");
            return;
        }
        
        int id;
        try
        {
            id = Integer.parseInt(IDTxt.getText());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Animal ID should be integer!");
            return;
        }
        
        for(StrayAnimal nowanimal:this.rescuecenter.getStrayanimalDir().getStrayAnimalDirectory()){
            if(nowanimal.getID() == id){
                JOptionPane.showMessageDialog(null, "ID has existed!");
                return;
            }
        }
        
        StrayAnimal strayanimal = rescuecenter.getStrayanimalDir().createStrayAnimal();
        strayanimal.setAddress(AddressTxt.getText());
        strayanimal.setDescription(DescriptionTxt.getText());
        strayanimal.setID(id);
        strayanimal.setSpecies(AnimalTypeTxt.getText());
        strayanimal.setStatus(StatusComboBox.getSelectedItem().toString());
        
        JOptionPane.showMessageDialog(null, "Create Stray Animal Successfully!");
        
        AddressTxt.setText("");
        DescriptionTxt.setText("");
        IDTxt.setText("");
        AnimalTypeTxt.setText("");
    }//GEN-LAST:event_CreateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField AnimalTypeTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JTextField DescriptionTxt;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
