/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.RescueCenter;

import Entity.Account.Account;
import Entity.Center.RescueCenter;
import Entity.Center.RescueCenterDirectory;
import Entity.Network.Network;
import Entity.System.EcoSystem;
import Interface.Hospital.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ManageCenterEmplyeeJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCenterEmplyeeJpanel
     */
    private JPanel registerpanel;
    private EcoSystem ecoSystem;
    private RescueCenter res;
    private Account account;
    public ManageCenterEmplyeeJpanel(JPanel registerpanel,EcoSystem ecoSystem, RescueCenter res) {
        initComponents();
        this.registerpanel = registerpanel;      
        this.ecoSystem = ecoSystem;
        this.res = res;
        SaveBtn.setEnabled(false);
        
        populate();
    }
    
    public void populate(){
        int rowCount = EmployeeTbl.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)EmployeeTbl.getModel();
        jScrollPane1.getViewport().setBackground(new Color(249,246,246));
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        
        for(Account a  : this.res.getEmployeeaccountDir().getAccountList()){
            Object row[] = new Object[dtm.getColumnCount()];
            row[0] = a;
            row[1] = a.getPassword();                      
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CreateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RepasswordTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/RescueCenter/Label.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, 140));

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateBtn.setBackground(new java.awt.Color(255, 255, 255));
        CreateBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CreateBtn.setText("Create");
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CreateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 304, 124, -1));

        EmployeeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "UserName", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmployeeTbl);
        if (EmployeeTbl.getColumnModel().getColumnCount() > 0) {
            EmployeeTbl.getColumnModel().getColumn(0).setResizable(false);
            EmployeeTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 91, 341, 206));

        jLabel1.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel1.setText("UserName：");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 107, 108, 32));

        UserNameTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jPanel2.add(UserNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 104, 197, 40));

        jLabel2.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel2.setText("Password：");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(438, 175, 100, 33));

        PasswordTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jPanel2.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 168, 197, 40));

        jLabel3.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel3.setText("Re_Password：");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 239, -1, 33));

        RepasswordTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jPanel2.add(RepasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 236, 197, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel5.setText("Manage Rescue Center Employee");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 630, -1));

        EditBtn.setBackground(new java.awt.Color(255, 255, 255));
        EditBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });
        jPanel2.add(EditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 328, 124, -1));

        DeleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.setPreferredSize(new java.awt.Dimension(75, 29));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 328, 124, -1));

        SaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        SaveBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 304, 124, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = EmployeeTbl.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Account acc = (Account)EmployeeTbl.getValueAt(selectedRow, 0);
            SaveBtn.setEnabled(true);
            UserNameTxt.setText(acc.getName());
            PasswordTxt.setText(acc.getPassword());
            RepasswordTxt.setText(acc.getPassword());
            CreateBtn.setEnabled(false);
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_EditBtnActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        if(UserNameTxt.getText().isEmpty() || PasswordTxt.getText().isEmpty() || RepasswordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some input text is empty!");
            UserNameTxt.setText("");
            PasswordTxt.setText("");
            RepasswordTxt.setText("");
            return;
        }
        
        if(!this.ecoSystem.newName(UserNameTxt.getText())){
            JOptionPane.showMessageDialog(null, "User name has existed!");
            return;
        }
        
        if(RepasswordTxt.getText().equalsIgnoreCase(PasswordTxt.getText())){
            this.account = this.res.getEmployeeaccountDir().createAccount();
            account.setName(UserNameTxt.getText());
            account.setPassword(PasswordTxt.getText());
            System.out.println(account.getName());
            System.out.println(res.getName());
            
        }
            else{
            JOptionPane.showMessageDialog(null, "Something Wrong, Please Check!");
            return;
        }
        JOptionPane.showMessageDialog(null, "Create Rescue Center Employee Successfully!");
        
        UserNameTxt.setText("");
        PasswordTxt.setText("");
        RepasswordTxt.setText("");
        populate();
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        int row = EmployeeTbl.getSelectedRow();
        
        if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select any row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Account a = (Account)EmployeeTbl.getValueAt(row, 0);
        res.getEmployeeaccountDir().deleteAccount(a);
        populate();
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:

        if(UserNameTxt.getText().isEmpty() || PasswordTxt.getText().isEmpty() || RepasswordTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some input text is empty!");
            UserNameTxt.setText("");
            PasswordTxt.setText("");
            RepasswordTxt.setText("");
            return;
        }
        
        if(RepasswordTxt.getText().equalsIgnoreCase(PasswordTxt.getText())){
            int selectedRow = EmployeeTbl.getSelectedRow();
        
        if(selectedRow >= 0)
        {
            Account acc = (Account)EmployeeTbl.getValueAt(selectedRow, 0);
            if(!this.ecoSystem.newName(UserNameTxt.getText())&& !UserNameTxt.getText().equals(acc.getName())){
                    JOptionPane.showMessageDialog(null, "User name has existed!");
                    return;
            }
            acc.setName(UserNameTxt.getText());
            acc.setPassword(PasswordTxt.getText());
            System.out.println(acc.getName());
            System.out.println(res.getName());
            
        }
        }
            else{
            JOptionPane.showMessageDialog(null, "Something Wrong, Please Check!");
            return;
        }
        JOptionPane.showMessageDialog(null, "Update Rescue Center Employee Successfully!");
        
        UserNameTxt.setText("");
        PasswordTxt.setText("");
        RepasswordTxt.setText("");
        SaveBtn.setEnabled(false);
        CreateBtn.setEnabled(true);
        populate();
    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JTable EmployeeTbl;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JTextField RepasswordTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
