/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.RescueCenter;

import Entity.Account.Account;
import Entity.Adopter.Adopter;
import Entity.AdopterCenter.AdopterCenter;
import Entity.Center.RescueCenter;
import Entity.Network.Network;
import Entity.Request.Request;
import Entity.StrayAnimal.StrayAnimal;
import Entity.System.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ManageApplicationJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageApplicationJpanel
     */
    private JPanel rightpanel;
    private EcoSystem ecoSystem;
    private RescueCenter res;
    
    public ManageApplicationJpanel(JPanel rightpanel, EcoSystem ecoSystem, RescueCenter res) {
        initComponents();
        this.rightpanel = rightpanel;
        this.ecoSystem = ecoSystem;
        this.res = res;
        
        populate();
    }
    
    public void populate()
    {
        int rowCount = ApplicationTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)ApplicationTable.getModel();
        jScrollPane1.getViewport().setBackground(new Color(249,246,246));
        for(int i = rowCount - 1; i >= 0; i--)
        {
            dtm.removeRow(i);
        }
        
        for(Request temp : this.res.getRequestDir().getRequestList()){
           Object row[] = new Object[dtm.getColumnCount()]; 
           row[0] = temp.getAdopter();
           row[1] = temp;
           row[2] = temp.getStrayanimal().getSpecies();
           row[3] = temp.getStrayanimal();
           row[4] = temp.getStrayanimal().getStatus();
           dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ApplicationTable = new javax.swing.JTable();
        AgreeBtn = new javax.swing.JButton();
        RejectBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setText("Manage Adopter Application Panel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 650, 55));

        ApplicationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Name", "Adopter Email", "Animal Type", "Animal ID", "Animal Health Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ApplicationTable);
        if (ApplicationTable.getColumnModel().getColumnCount() > 0) {
            ApplicationTable.getColumnModel().getColumn(0).setResizable(false);
            ApplicationTable.getColumnModel().getColumn(1).setResizable(false);
            ApplicationTable.getColumnModel().getColumn(2).setResizable(false);
            ApplicationTable.getColumnModel().getColumn(3).setResizable(false);
            ApplicationTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 720, 230));

        AgreeBtn.setBackground(new java.awt.Color(255, 255, 255));
        AgreeBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        AgreeBtn.setText("Agree");
        AgreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AgreeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 140, -1));

        RejectBtn.setBackground(new java.awt.Color(255, 255, 255));
        RejectBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        RejectBtn.setText("Reject");
        RejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RejectBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 148, -1));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BackBtn.setText("Back <<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 430));

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/RescueCenter/Label.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 120));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 850, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void RejectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ApplicationTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {      
            Request nowRequest = (Request)ApplicationTable.getValueAt(selectedRow, 1);
            this.res.getRequestDir().deleteRequest(nowRequest);
            JOptionPane.showMessageDialog(null, "Delete Request Successfully!");
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        
        populate();
    }//GEN-LAST:event_RejectBtnActionPerformed

    private void AgreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreeBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = ApplicationTable.getSelectedRow();
        
        if(selectedRow >= 0)
        {      
            Adopter nowAdopter = (Adopter)ApplicationTable.getValueAt(selectedRow, 0);
            StrayAnimal nowAnimal = (StrayAnimal) ApplicationTable.getValueAt(selectedRow, 3);
            Request nowH = (Request)ApplicationTable.getValueAt(selectedRow, 1);
            if(this.res.getStrayanimalDir().getStrayAnimalDirectory().contains(nowAnimal)){
                nowAdopter.getAnimalDir().addStrayAnimal(nowAnimal);
                this.res.getRequestDir().deleteRequest(nowH);
                this.res.getStrayanimalDir().deleteStrayAnimal(nowAnimal);
                JOptionPane.showMessageDialog(null, "Confirm Request Successfully!");
            }else{
                this.res.getRequestDir().deleteRequest(nowH);
                JOptionPane.showMessageDialog(null, "This animal donnot exist in this rescue center, maybe it has been deleted or adopted!");
            }
            
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
        
        populate();
    }//GEN-LAST:event_AgreeBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        
        rightpanel.remove(this);
        Component[] componentArray = rightpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageRescueCenterJpanel mfpanel = (ManageRescueCenterJpanel) component;
        mfpanel.populate();
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
        
        
//        this.rightpanel.remove(this);
//        CardLayout cardlayout =  (CardLayout)this.rightpanel.getLayout();
//        cardlayout.previous(rightpanel);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgreeBtn;
    private javax.swing.JTable ApplicationTable;
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton RejectBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
