/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.RescueCenter;

import Entity.Account.Account;
import Entity.Center.RescueCenter;
import Entity.Center.RescueCenterDirectory;
import Entity.EnterpriseDirectory.EnterpriseDirectory;
import Entity.Hospital.PetHospital;
import Entity.Hospital.PetHospitalDirectory;
import Entity.Network.Network;
import Entity.StrayAnimal.StrayAnimalDirectory;
import Entity.System.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class RescueCenterLoginJpanel extends javax.swing.JPanel {

    /**
     * Creates new form RescueCenterLoginJpanel
     */
    private JPanel rightpanel;
    private EcoSystem ecoSystem;
    private PetHospitalDirectory petHospitalDirectory;
    
    public RescueCenterLoginJpanel(JPanel rightpanel, EcoSystem ecoSystem, PetHospitalDirectory petHospitalDirectory) {
        initComponents();
        this.rightpanel = rightpanel;
        this.ecoSystem = ecoSystem;
        this.petHospitalDirectory = petHospitalDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CenterNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PasswordTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        UserNameTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(881, 606));
        setPreferredSize(new java.awt.Dimension(881, 614));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/RescueCenter/Label.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 820, 130));

        jLabel2.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel2.setText("Rescue Center Name：");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, 33));

        CenterNameTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        add(CenterNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 226, 39));

        jLabel4.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 36)); // NOI18N
        jLabel4.setText("Rescue Center Login Panel");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 439, 67));

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 140));

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jPanel2.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 226, 39));

        jLabel3.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel3.setText("      Password：");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, 33));

        LoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        LoginBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 230, -1));

        jLabel5.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel5.setText("UserName：");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, 33));

        UserNameTxt.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jPanel2.add(UserNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 226, 39));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 830, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:

    for(Network nn : this.ecoSystem.getNetworkDir().getNetworkList()){
        for(RescueCenter nr : nn.getEnterpriseDir().getRescuecenterDir().getRcd()){
            if(nr.getName().equals(CenterNameTxt.getText()) && nr.getManageraccountDir().VerifyAccount(UserNameTxt.getText() , PasswordTxt.getText())){
                    JOptionPane.showMessageDialog(null, "Login as a Manager Successfully!");
                        ManageCenterEmplyeeJpanel mrcipanel = new ManageCenterEmplyeeJpanel(rightpanel,ecoSystem, nr);       
                        rightpanel.add(mrcipanel);
                        CardLayout layout = (CardLayout)rightpanel.getLayout();
                        layout.next(rightpanel);
                        return;
            }else if
                (nr.getName().equals(CenterNameTxt.getText()) && nr.getEmployeeaccountDir().VerifyAccount(UserNameTxt.getText() , PasswordTxt.getText())){
                    JOptionPane.showMessageDialog(null, "Login as an Enployee successfully!");
                        ManageRescueCenterJpanel mrcpanel = new ManageRescueCenterJpanel(rightpanel,ecoSystem, nr, petHospitalDirectory);       
                        rightpanel.add(mrcpanel);
                        CardLayout layout = (CardLayout)rightpanel.getLayout();
                        layout.next(rightpanel);
                        return; 
                        }
                    }
            }
    
        JOptionPane.showMessageDialog(null, "Something Wrong, Please Check!");
    }//GEN-LAST:event_LoginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CenterNameTxt;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JTextField UserNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
