/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Adopter;

import Entity.Account.Account;
import Entity.Adopter.Adopter;
import Entity.Adopter.AdopterDirectory;
import Entity.AdopterCenter.AdopterCenter;
import Entity.AdopterCenter.AdopterCenterDirectory;
import Entity.Network.Network;
import Entity.System.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class AdopterRegisterJpanel extends javax.swing.JPanel {

    /**
     * Creates new form AdopterRegisterJpanel
     */
    private JPanel registerpanel;
    private EcoSystem ecoSystem;
    private AdopterDirectory adopterDirectory;
           
    public AdopterRegisterJpanel(JPanel registerpanel, EcoSystem ecoSystem, AdopterDirectory adopterDirectory) {
        initComponents();
        this.registerpanel = registerpanel;
        this.ecoSystem = ecoSystem;
        this.adopterDirectory = adopterDirectory;
        
        populate();
    }
    
    public void populate()
    {
        int rowCount = adoptercenterTbl.getRowCount();
        jScrollPane1.getViewport().setBackground(new Color(249,246,246));
        DefaultTableModel dtm = (DefaultTableModel)adoptercenterTbl.getModel();
        for(int i = rowCount - 1; i >= 0; i--)
        {
            dtm.removeRow(i);
        }
        
        for(Network network : this.ecoSystem.getNetworkDir().getNetworkList())
        {
            for(AdopterCenter adopterCenter : network.getEnterpriseDir().getAdoptercenterDir().getAdopterCenterDir())
            {
                Object row[] = new Object[dtm.getColumnCount()];
                row[0] = adopterCenter;
                row[1] = adopterCenter.getAddress();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdopterNameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Re_PasswordTxt = new javax.swing.JTextField();
        RegisterBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adoptercenterTbl = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(881, 614));

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 36)); // NOI18N
        jLabel4.setText("Adopter Register Panel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 480, 67));

        jLabel2.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel2.setText("UserName：");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, 33));
        jPanel1.add(AdopterNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 226, 39));
        jPanel1.add(PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 226, 39));

        jLabel3.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel3.setText("      Password：");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 33));

        jLabel7.setFont(new java.awt.Font("Mshtakan", 1, 18)); // NOI18N
        jLabel7.setText("     Re_Password：");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, 33));
        jPanel1.add(Re_PasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 226, 39));

        RegisterBtn.setBackground(new java.awt.Color(255, 255, 255));
        RegisterBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 230, -1));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BackBtn.setText("Back <<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, -1));

        adoptercenterTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adopter Center Name", "Adopter Center Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(adoptercenterTbl);
        if (adoptercenterTbl.getColumnModel().getColumnCount() > 0) {
            adoptercenterTbl.getColumnModel().getColumn(0).setResizable(false);
            adoptercenterTbl.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 470, 140));

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Adopter/AdopterLogin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.registerpanel.remove(this);
        CardLayout cardlayout = (CardLayout)this.registerpanel.getLayout();
        cardlayout.previous(registerpanel);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        if(AdopterNameTxt.getText().isEmpty() || PasswordTxt.getText().isEmpty() || Re_PasswordTxt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Some input text is empty!");
            AdopterNameTxt.setText("");
            PasswordTxt.setText("");
            Re_PasswordTxt.setText("");
            return;
        }
        
        if(!this.ecoSystem.newName(AdopterNameTxt.getText())){
            JOptionPane.showMessageDialog(null, "User name has existed!");
            return;
        }
        
        if(Re_PasswordTxt.getText().equals(PasswordTxt.getText()))
        {
            int selectedRow = adoptercenterTbl.getSelectedRow();
            if(selectedRow >= 0)
            {
                AdopterCenter adopterCenter = (AdopterCenter)adoptercenterTbl.getValueAt(selectedRow, 0);
                Adopter adopter = adopterCenter.getAdopterDir().createAdopter();
                Account account = new Account();
                account.setName(AdopterNameTxt.getText());
                account.setPassword(PasswordTxt.getText());
                adopter.setAccount(account);
            }
            
            else
            {
                JOptionPane.showMessageDialog(null, "Please select any row!!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(null, "Something Wrong, Please Check!");
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Create Adopter Successfully!");
        
        AdopterNameTxt.setText("");
        PasswordTxt.setText("");
        Re_PasswordTxt.setText("");
    }//GEN-LAST:event_RegisterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdopterNameTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JTextField Re_PasswordTxt;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JTable adoptercenterTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
