/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Adopter;

import Entity.Adopter.Adopter;
import Entity.Adopter.AdopterInfo;
import Entity.EmailOperation.EmailSection;
import Entity.System.EcoSystem;
import Interface.RescueCenter.ManageRescueCenterJpanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class InformationJpanel extends javax.swing.JPanel {

    /**
     * Creates new form InformationJpanel
     */
    private JPanel informationpanel;
    private EcoSystem ecoSystem;
    private Adopter adopter;
    private EmailSection emailOP;
    
    public InformationJpanel(JPanel informationpanel, EcoSystem ecoSystem, Adopter adopter) {
        initComponents();
        this.informationpanel = informationpanel;
        this.ecoSystem = ecoSystem;
        this.adopter = adopter;
        this.emailOP = new  EmailSection();
        populate();
    }
    
    public void populate(){
        LastNameTxt.setText(this.adopter.getUserInfo().getLastName());
        FirstNameTxt.setText(this.adopter.getUserInfo().getFirstName());
        AgeTxt.setText(this.adopter.getUserInfo().getAge()+"");
        EmailTxt.setText(this.adopter.getUserInfo().getEmail());
        TelTxt.setText(this.adopter.getUserInfo().getPhoneNumber());
        SalaryTxt.setText(this.adopter.getUserInfo().getSalary()+"");
        AddressTxt.setText(this.adopter.getUserInfo().getAddressLine());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FirstNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AgeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TelTxt = new javax.swing.JTextField();
        SalaryTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        dogCb = new javax.swing.JCheckBox();
        catCb = new javax.swing.JCheckBox();
        birdCb = new javax.swing.JCheckBox();
        rabbitCb = new javax.swing.JCheckBox();
        mouseCb = new javax.swing.JCheckBox();
        snackCb = new javax.swing.JCheckBox();
        backBtn = new javax.swing.JButton();
        verifyTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        VerifyBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(881, 614));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 246, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Adopter/image.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        jLabel2.setText("Please fill in your information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 6, 690, 120));

        jPanel3.setBackground(new java.awt.Color(249, 246, 246));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Last Name：");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("First Name：");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("          Age：");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Email：");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Tel：");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setText("Salary：");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setText("Location Address：");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("Animal You Already Haved：");

        SubmitBtn.setBackground(new java.awt.Color(255, 255, 255));
        SubmitBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        dogCb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        dogCb.setText("Dog");

        catCb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        catCb.setText("Cat");

        birdCb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        birdCb.setText("Bird");

        rabbitCb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rabbitCb.setText("Rabbit");

        mouseCb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        mouseCb.setText("Mouse");

        snackCb.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        snackCb.setText("Snack");

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backBtn.setText("Back <<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setText("Verify Code：");

        VerifyBtn.setBackground(new java.awt.Color(255, 255, 255));
        VerifyBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        VerifyBtn.setText("Verify");
        VerifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SalaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(verifyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(VerifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dogCb)
                                    .addComponent(catCb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rabbitCb)
                                        .addGap(18, 18, 18)
                                        .addComponent(birdCb))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(mouseCb)
                                        .addGap(18, 18, 18)
                                        .addComponent(snackCb))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(105, 105, 105))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catCb)
                            .addComponent(mouseCb)
                            .addComponent(snackCb)))
                    .addComponent(dogCb)
                    .addComponent(rabbitCb)
                    .addComponent(birdCb))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerifyBtn))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addComponent(SubmitBtn)))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 132, 860, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        if(LastNameTxt.getText().isEmpty() || FirstNameTxt.getText().isEmpty() || AgeTxt.getText().isEmpty() || EmailTxt.getText().isEmpty() || TelTxt.getText().isEmpty() || SalaryTxt.getText().isEmpty() || AddressTxt.getText().isEmpty() || verifyTxt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Some input text is empty!");
//            LastNameTxt.setText("");
//            FirstNameTxt.setText("");
//            AgeTxt.setText("");
//            EmailTxt.setText("");
//            TelTxt.setText("");
//            SalaryTxt.setText("");
//            AddressTxt.setText("");
//            verifyTxt.setText("");
            return;
        }
        
        else
        {
            if(!verifyTxt.getText().equals(String.valueOf(this.emailOP.getConfirmCode()))){
                JOptionPane.showMessageDialog(null, "Confirm Error!");
                return;
            }
            int age;
            try
            {
                age = Integer.parseInt(AgeTxt.getText());
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Adopter age should be integer!");
                return;
            }
            
            int salary;
            try
            {
                salary = Integer.parseInt(SalaryTxt.getText());
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Adopter salary should be integer!");
                return;
            }
            
            AdopterInfo adopterInfo = this.adopter.getUserInfo();
            adopterInfo.setLastName(LastNameTxt.getText());
            adopterInfo.setFirstName(FirstNameTxt.getText());
            adopterInfo.setAge(age);
            adopterInfo.setEmail(EmailTxt.getText());
            adopterInfo.setPhoneNumber(TelTxt.getText());
            adopterInfo.setSalary(salary);
            adopterInfo.setAddressLine(AddressTxt.getText());
            ArrayList animalList = new ArrayList<String>();
            if(dogCb.isSelected())
            {
                animalList.add("Dog");
            }
            
            if(catCb.isSelected())
            {
                animalList.add("Cat");
            }
            
            if(rabbitCb.isSelected())
            {
                animalList.add("Rabbit");
            }
                    
            if(mouseCb.isSelected())
            {
                animalList.add("Mouse");
            }
            
            if(birdCb.isSelected())
            {
                animalList.add("Bird");
            }
            
            if(snackCb.isSelected())
            {
                animalList.add("Snack");
            }
            
            adopterInfo.setTypeList(animalList);
            adopter.setStatus("Pending");
            
            JOptionPane.showMessageDialog(null, "Create Adopter Information Successfully!");
            
//            LastNameTxt.setText("");
//            FirstNameTxt.setText("");
//            AgeTxt.setText("");
//            EmailTxt.setText("");
//            TelTxt.setText("");
//            SalaryTxt.setText("");
//            AddressTxt.setText("");
//            verifyTxt.setText("");
//            this.VerifyBtn.setEnabled(true);
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.informationpanel.remove(this);
        Component[] componentArray = informationpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CheckStatusJpanel cspanel = (CheckStatusJpanel) component;
        cspanel.populate();
        CardLayout cardlayout =  (CardLayout)this.informationpanel.getLayout();
        cardlayout.previous(informationpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void VerifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyBtnActionPerformed
        // TODO add your handling code here:
        String emailaddress = this.EmailTxt.getText();
        if(emailaddress.equals("")){
            JOptionPane.showMessageDialog(null, "Email addres is empty, please input!");
            return;
        }
        
        try{
            this.emailOP.sendEmail(emailaddress);
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Email sending fails!");
            return;
        }
        JOptionPane.showMessageDialog(null, "Email has been sent successfully!");
        this.VerifyBtn.setEnabled(false);
    }//GEN-LAST:event_VerifyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JTextField SalaryTxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField TelTxt;
    private javax.swing.JButton VerifyBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JCheckBox birdCb;
    private javax.swing.JCheckBox catCb;
    private javax.swing.JCheckBox dogCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox mouseCb;
    private javax.swing.JCheckBox rabbitCb;
    private javax.swing.JCheckBox snackCb;
    private javax.swing.JTextField verifyTxt;
    // End of variables declaration//GEN-END:variables
}
