/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Adopter;

import Entity.StrayAnimal.StrayAnimal;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class ViewAnimalDetailsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAnimalDetailsJpanel
     */
    private JPanel rightpanel;
    private StrayAnimal strayAnimal;
    
    public ViewAnimalDetailsJpanel(JPanel rightpanel, StrayAnimal strayAnimal) {
        initComponents();
        this.rightpanel = rightpanel;
        this.strayAnimal = strayAnimal;
        
        AnimalTypeTxt.setText(strayAnimal.getSpecies());
        AddressTxt.setText(strayAnimal.getAddress());
        StatusTxt.setText(strayAnimal.getStatus());
        IDTxt.setText(Integer.toString(strayAnimal.getID()));
        DescriptionTxt.setText(strayAnimal.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        StatusTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDTxt = new javax.swing.JTextField();
        AnimalTypeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AddressTxt = new javax.swing.JTextField();
        DescriptionTxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(249, 246, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Animal Species:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 147, 32));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Description：");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 135, 28));

        StatusTxt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(StatusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 215, 38));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("ID：");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Status：");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 30));

        IDTxt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 215, 38));

        AnimalTypeTxt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(AnimalTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 215, 37));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Address of Find：");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 173, 31));

        AddressTxt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(AddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 215, 36));

        DescriptionTxt.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jPanel2.add(DescriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 215, 160));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        BackBtn.setText("Back <<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel2.add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 410));

        jPanel3.setBackground(new java.awt.Color(249, 246, 246));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/RescueCenter/Label.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 120));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 850, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.rightpanel.remove(this);
        CardLayout cardlayout = (CardLayout)this.rightpanel.getLayout();
        cardlayout.previous(rightpanel);
        
        AnimalTypeTxt.setText("");
        AddressTxt.setText("");
        StatusTxt.setText("");
        IDTxt.setText("");
        DescriptionTxt.setText("");
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxt;
    private javax.swing.JTextField AnimalTypeTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DescriptionTxt;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JTextField StatusTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
